# Generated by Django 3.2.11 on 2022-01-17 23:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('on_hold', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('in_stock', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('restocking_cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('min_quantity_in_stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('user_uploaded_image', models.ImageField(default='images/karting.jpg', upload_to='images/')),
                ('last_updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
